apt install python3-pip
pkg install python3
pip3 install setuptools
pip3 install rsa
pip3 install thrift==0.11.0
pip3 install requests
pip3 install bs4
pip3 install gtts
pip3 install pytz
pip3 install humanfriendly
pip3 install googletrans
pip3 install nano
pip3 install null
pip3 install humanize
pip3 install html5lib
pip3 install wikipedia
pip3 install youtube_dl
pip3 install livejson
pip3 install pafy
pip3 install akad
pip3 install null
pip3 install Naked
pip3 install subprocess
pip3 install youtube_dl
pip3 install humanize
pip3 install traceback